name: Create Release

on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'The new tag to create (e.g., v0.4.0)'
        required: true
      previous_tag:
        description: 'The previous tag for changelog generation (e.g., v0.3.58)'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # To push tags, branches, and commits
      pull-requests: write # To create and merge pull requests
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: 'master'
          fetch-depth: 0 # Required for changelog generation from git history

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push new tag
        run: |
          git tag ${{ github.event.inputs.new_tag }}
          git push origin ${{ github.event.inputs.new_tag }}
        
      - name: Create ci_release branch
        run: |
          git checkout -b ci_release_${{ github.event.inputs.new_tag }}

      - name: Generate changelog
        env:
          GH_TOKEN: ${{ github.token }}
          NEW_TAG: ${{ github.event.inputs.new_tag }}
          PREVIOUS_TAG: ${{ github.event.inputs.previous_tag }}
        run: |
          echo "## Changelog for $NEW_TAG" > changelog.md
          echo "" >> changelog.md
          gh api repos/${{ github.repository }}/compare/${PREVIOUS_TAG}...${NEW_TAG} --jq '.commits[] | "- \(.commit.message | split("\n")[0]) (by @\(.author.login // .commit.author.name) in `\(.sha | tostring | .[0:7])`) "' >> changelog.md
          mkdir -p CHANGELOGS
          mv changelog.md CHANGELOGS/${NEW_TAG}-release.md

      - name: Commit and push changelog
        run: |
          git add CHANGELOGS/${{ github.event.inputs.new_tag }}-release.md
          git commit -m "docs(changelog): Generate changelog for ${{ github.event.inputs.new_tag }}"
          git push --set-upstream origin ci_release_${{ github.event.inputs.new_tag }}

      - name: Create Changelog Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
          NEW_TAG: ${{ github.event.inputs.new_tag }}
        run:  |
          gh pr create --title "docs(changelog): Generate changelog for ${NEW_TAG}" --body "Generate changelog for ${NEW_TAG}" --base master --head ci_release_${NEW_TAG}
          gh pr merge --auto --squash # --delete-branch
