name: Promote Release Branch

on:
  workflow_dispatch:
    inputs:
      current_tag:
        description: 'The tag of the release to promote (e.g., v0.4.0). This should match the tag used in the first workflow.'
        required: true

jobs:
  rename_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push and delete branches
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rename release branch
        env:
          CURRENT_TAG: ${{ github.event.inputs.current_tag }}
        run: |
          OLD_BRANCH="ci_release_${CURRENT_TAG}"
          NEW_BRANCH="release_${CURRENT_TAG}"
          
          echo "Fetching ${OLD_BRANCH}..."
          git fetch origin ${OLD_BRANCH}:${OLD_BRANCH}
          
          echo "Pushing commit to ${NEW_BRANCH}..."
          # Create the new branch pointing to the same commit as the old branch
          git push origin refs/heads/${OLD_BRANCH}:refs/heads/${NEW_BRANCH}
          
          echo "Deleting old branch ${OLD_BRANCH}..."
          git push origin --delete ${OLD_BRANCH}
