name: Create Release

on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'The new tag(version) to create (e.g., v0.4.0)'
        required: true
      previous_tag:
        description: 'The previous tag for changelog generation (e.g., v0.3.58)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code from selected branch
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0 # Required for changelog generation from git history

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate changelog
        env:
          ARK_MODEL_ENDPOINT: ${{ secrets.ARK_MODEL_ENDPOINT }}
          ARK_API_KEY: ${{ secrets.ARK_API_KEY }}
          ARK_MODEL_NAME: ${{ env.ARK_MODEL_NAME }}
          NEW_TAG: ${{ github.event.inputs.new_tag }}
          PREVIOUS_TAG: ${{ github.event.inputs.previous_tag }}
          RELEASE_BRANCH: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          COMMIT_LOGS=$(gh api repos/${{ github.repository }}/compare/${PREVIOUS_TAG}...${RELEASE_BRANCH} --jq '.commits[] | "- \(.commit.message | split("\n")[0]) (by @\(.author.login // .commit.author.name) in `\(.sha | tostring | .[0:7])`) "')
          echo "$COMMIT_LOGS" | python scripts/generate_changelog.py $NEW_TAG $PREVIOUS_TAG > changelog.md
          mkdir -p CHANGELOGS
          mv changelog.md CHANGELOGS/${NEW_TAG}-release.md

      - name: Update version in pyproject.toml
        run: |
          # Remove 'v' prefix from tag if present (e.g., v0.4.0 -> 0.4.0)
          VERSION=${{ github.event.inputs.new_tag }}
          VERSION=${VERSION#v}

          # Update version in pyproject.toml
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml

      - name: Commit version bump and changelog
        run: |
          git add pyproject.toml CHANGELOGS/${{ github.event.inputs.new_tag }}-release.md
          git commit -m "chore(release): prepare release ${{ github.event.inputs.new_tag }}"
          git push origin ${{ github.ref_name }}

      - name: Push Changelog to changelog branch
        run: |
          git fetch origin changelog || echo "changelog branch does not exist, will create it."
          git switch changelog || git switch -c changelog
          git checkout ${{ github.ref_name }} -- CHANGELOGS/${{ github.event.inputs.new_tag }}-release.md
          git add CHANGELOGS/${{ github.event.inputs.new_tag }}-release.md
          git commit -m "docs: add changelog for ${{ github.event.inputs.new_tag }}"
          git push origin changelog
          # Switch back to the original branch to not affect subsequent steps
          git switch ${{ github.ref_name }}

      - name: Create and push tag
        run: |
          git tag ${{ github.event.inputs.new_tag }}
          git push origin ${{ github.event.inputs.new_tag }}

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.event.inputs.new_tag }} \
            --title "Release ${{ github.event.inputs.new_tag }}" \
            --notes-file "CHANGELOGS/${{ github.event.inputs.new_tag }}-release.md"
